### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by Yrlec** [nativelibs4java/BridJ#65]
I'm having problems initializing BridJ on Android. I'm running Android 4.4 (the arm emulator) and BridJ 0.7. Here's the stack trace:

05-13 12:15:20.434    1245-1245/com.degoo.android W/System.err﹕ java.lang.RuntimeException: Failed to initialize BridJ (java.lang.UnsatisfiedLinkError: Couldn't load bridj from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.degoo.android-1.apk", zip file "/data/data/com.degoo.android/code_cache/secondary-dexes/com.degoo.android-1.apk.classes2.zip", zip file "/data/data/com.degoo.android/code_cache/secondary-dexes/com.degoo.android-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.degoo.android-1, /system/lib]]]: findLibrary returned null)
05-13 12:15:20.434    1245-1245/com.degoo.android W/System.err﹕ at org.bridj.Platform.initLibrary(Platform.java:444)
05-13 12:15:20.434    1245-1245/com.degoo.android W/System.err﹕ at org.bridj.Platform.<clinit>(Platform.java:228)
05-13 12:15:20.434    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform.getPathMatchingPattern(Platform.java:348)
05-13 12:15:20.444    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform.addPattern(Platform.java:337)
05-13 12:15:20.444    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.LinuxPlatform.<init>(LinuxPlatform.java:40)
05-13 12:15:20.444    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform.createCurrentPlatform(Platform.java:183)
05-13 12:15:20.444    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform.access$000(Platform.java:23)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform$LazyHolder.<clinit>(Platform.java:167)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.platform.Platform.getInstance(Platform.java:171)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.android.guice.AndroidModule.configure(AndroidModule.java:12)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.spi.Elements.getElements(Elements.java:110)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
05-13 12:15:20.454    1245-1245/com.degoo.android W/System.err﹕ at com.google.inject.Guice.createInjector(Guice.java:96)
05-13 12:15:20.464    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.android.guice.InjectorFactory.createProductionInjector(InjectorFactory.java:27)
05-13 12:15:20.464    1245-1245/com.degoo.android W/System.err﹕ at com.degoo.android.MainActivity.onCreate(MainActivity.java:22)
05-13 12:15:20.464    1245-1245/com.degoo.android W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5231)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
05-13 12:15:20.474    1245-1245/com.degoo.android W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5017)
05-13 12:15:20.494    1245-1245/com.degoo.android W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
05-13 12:15:20.494    1245-1245/com.degoo.android W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
05-13 12:15:20.494    1245-1245/com.degoo.android W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-13 12:15:20.494    1245-1245/com.degoo.android W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-13 12:15:20.504    1245-1245/com.degoo.android W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
05-13 12:15:20.504    1245-1245/com.degoo.android W/System.err﹕ Caused by: java.lang.UnsatisfiedLinkError: Couldn't load bridj from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.degoo.android-1.apk", zip file "/data/data/com.degoo.android/code_cache/secondary-dexes/com.degoo.android-1.apk.classes2.zip", zip file "/data/data/com.degoo.android/code_cache/secondary-dexes/com.degoo.android-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.degoo.android-1, /system/lib]]]: findLibrary returned null
05-13 12:15:20.514    1245-1245/com.degoo.android W/System.err﹕ at java.lang.Runtime.loadLibrary(Runtime.java:358)
05-13 12:15:20.514    1245-1245/com.degoo.android W/System.err﹕ at java.lang.System.loadLibrary(System.java:526)
05-13 12:15:20.514    1245-1245/com.degoo.android W/System.err﹕ at org.bridj.Platform.initLibrary(Platform.java:428)
05-13 12:15:20.524    1245-1245/com.degoo.android W/System.err﹕ ... 31 more
05-13 12:15:20.524    1245-1245/com.degoo.android W/dalvikvm﹕ No implementation found for native Lorg/bridj/Platform;.sizeOf_ptrdiff_t:()I
05-13 12:15:20.524    1245-1245/com.degoo.android W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bridj/Platform;
05-13 12:15:20.524    1245-1245/com.degoo.android W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/degoo/platform/Platform$LazyHolder;
05-13 12:15:20.524    1245-1245/com.degoo.android D/AndroidRuntime﹕ Shutting down VM

I've defined the Maven dependency like this:
```
<groupId>com.nativelibs4java</groupId>
 <artifactId>bridj</artifactId>
 <version>0.7.0</version>
```

Any idea on what's causing this?

**Comment by Yrlec** [comment]
I should add that we're using multiple dex files. Could that the reason for this issue?

**Comment by Yrlec** [comment]
I have some more info now. I've tried with multidex disabled but that didn't make any difference. However, I did notice that bridj-0.7.0-android.jar doesn't have a libs/armeabi folder. I guess that's the issue. How do I make sure that libbridj.so gets added to libs/armeabi in the final jar?
